# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 08:42
from __future__ import unicode_literals

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('message', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=15)),
                ('id', models.IntegerField(primary_key=builtins.id, serialize=False)),
            ],
        ),
    ]
