# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 08:59
from __future__ import unicode_literals

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('message', models.TextField()),
                ('time', models.CharField(max_length=15)),
                ('id', models.IntegerField(primary_key=builtins.id, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
