# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20170908_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='title',
            field=models.CharField(default='没有标题', max_length=50),
            preserve_default=False,
        ),
    ]
