# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 09:11
from __future__ import unicode_literals

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_auto_20170908_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gupiao',
            fields=[
                ('id', models.IntegerField(primary_key=builtins.id, serialize=False)),
                ('num', models.IntegerField(max_length=10)),
                ('short_name', models.TextField()),
                ('title', models.CharField(max_length=15)),
                ('href', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Cninfo',
        ),
    ]
