# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 13:06
from __future__ import unicode_literals

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0005_auto_20170908_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Db',
            fields=[
                ('id', models.IntegerField(auto_created=1, primary_key=builtins.id, serialize=False)),
                ('num', models.CharField(max_length=9)),
                ('short_name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=40)),
                ('href', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Gupiao',
        ),
    ]
