# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0008_auto_20170909_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gupiao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=10)),
                ('short_name', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('href', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
